services:
    telegram:
        image: telegram-gpu
        build:
            dockerfile: ./telegram/Dockerfile-gpu
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: all
                            capabilities: [gpu]
        env_file:
            - .env
        environment:
            - BOT_TOKEN = ${BOT_TOKEN}
            - NVIDIA_VISIBLE_DEVICES = all
            - NVIDIA_DRIVER_CAPABILITIES = compute,utility
