FROM python:3.12-slim

WORKDIR /app

COPY ./telegram/requirements.txt tele-reqs.txt
COPY ../requirements.txt pozd-reqs.txt

RUN pip3 install -r tele-reqs.txt
RUN pip3 install -r pozd-reqs.txt

COPY ./telegram ./telegram
COPY ./pozdnyakov ./telegram/pozdnyakov

CMD ["python", "telegram/main.py"]
